### ISSUE TITLE
Feed doesn't load new newsletters

### ISSUE THREAD

**Issue by martinsrna** [nicholaschiang/hammock#41] opened 2021-05-18 07:48 UTC
I have new messages with the Hammock label in Gmail, but they don't show up in the feed.

Is there any push / pull mechanism we can use here so the feed is always up to date?

After logging out & logging in, they are there.

![image](https://user-images.githubusercontent.com/80906500/118611499-e75e0300-b78a-11eb-9625-79620b7663ed.png)

**Comment by nicholaschiang** [comment] 2021-05-18 15:39
Closing as a duplicate of #38.

**Closed by nicholaschiang** 2021-05-18 15:39 UTC
Labels: bug, p1

**Comment by martinsrna** [comment] 2021-05-18 15:42
Ah sorry! Forgot it's the same thing as yesterday.
